<?
$aMenuLinks = Array(
	Array(
		"РћС‚С‡РµС‚", 
		"/e-store/affiliates/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Р�РЅСЃС‚СЂСѓРєС†РёРё", 
		"/e-store/affiliates/instructions.php", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Р РµРіРёСЃС‚СЂР°С†РёСЏ", 
		"/e-store/affiliates/register.php", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"РџР»Р°РЅС‹", 
		"/e-store/affiliates/plans.php", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"РћС‚С‡РµС‚ РїРѕ РїСЂРѕРіСЂР°РјРјРµ", 
		"/e-store/affiliates/report.php", 
		Array(), 
		Array(), 
		"" 
	)
);
?>